server:
  port: 8090
  context-path: /

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    health:
      heck:
        enable: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

ding:
  talk:
    api:
      url: https://oapi.dingtalk.com/robot/send?access_token=
      token:
        dev: d6c53c81137595127536cf309039d7897eeceef02cd94b340e3bb74543d65e04
        research: 905308318f09e5436b4bf4ee66731cd1109edec64abd0eff43e4855f6931f27e


#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"