server:
  port: 8090
  context-path: /

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://192.168.11.91:8061/eureka/
    health:
      heck:
        enable: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

ding:
  talk:
    api:
      url: https://oapi.dingtalk.com/robot/send?access_token=
      token:
        dev: d6c53c81137595127536cf309039d7897eeceef02cd94b340e3bb74543d65e04#
        research: e158f2bb73f0e6cb4e9ad07953137a50f20c85f7a9c2a6946ea681ac7dce7710#


#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
