version: "2.1"

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:

  config-service:
    image: config-service:latest
    container_name: config-service-local
    hostname: config-service-local
    networks:
      - front-tier
      - back-tier
    ports:
      - 8088:8088
    environment:
      - "TZ=Asia/Shanghai"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/actuator/info"]
      interval: 30s
      timeout: 10s
      retries: 5

  discovery-service:
    image: discovery-service:latest
    container_name: discovery-service-local
    hostname: discovery-service-local
    ports:
      - 8061:8061
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8061/actuator/info"]
      interval: 30s
      timeout: 10s
      retries: 5

#    links:
#      - elasticsearch:elasticsearch
    depends_on:
      config-service:
        condition: service_healthy
    environment:
      - "TZ=Asia/Shanghai"
    networks:
      - front-tier
      - back-tier

  message-service:
    image: message-service:latest
    container_name: message-service-local
    hostname: message-service-local
    ports:
      - 8089:8089
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/actuator/info"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    environment:
      - "TZ=Asia/Shanghai"
    networks:
      - front-tier
      - back-tier

  notification-service:
    image: notification-service:latest
    container_name: notification-service-local
    hostname: notification-service-local
    ports:
      - 8090:8090
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/info"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    environment:
      - "TZ=Asia/Shanghai"
    networks:
      - front-tier
      - back-tier

  web-ui-service:
    image: web-ui-service:latest
    container_name: web-ui-service-local
    hostname: web-ui-service-local
    ports:
      - 8091:8091
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/actuator/info"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    environment:
      - "TZ=Asia/Shanghai"
    networks:
      - front-tier
      - back-tier